openapi: '3.0.2'
info:
  title: System of Economy
  description: This service allows for control of the system's Economy
  version: "1.0"
  contact:
    name: Juan Alexis Luque Ayala
    email: juan.luque.ayala@gmail.com
servers:
  - url:  https://link.herokuapp.com/

tags:
  - name: Concept
    description: Everything about Concept
  - name: Student 
    description: Everything about Student 
        
paths:
  #Modulo de Concepts
  /concepts:
    get:
      tags:
        - Concept    
      summary: Find all Concepts
      operationId: listConcepts
      responses:            
        '200':
          $ref: components/responses/responses.yml#/ShowConcepts         
        '404':          
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 
          
          
    post:
      tags:
        - Concept    
      summary: Add a new Concept to the system
      operationId: addConcept
      requestBody:
        description: Concept to add to the system
        content:
          application/json:
            schema:
              $ref: components/schemas/payloads/payload.yml#/ConceptPayload
      responses:      
        '201':
          $ref: components/responses/responses.yml#/CreatedConcept         
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 
        '422':
          $ref: components/responses/responses.yml#/UnprocessableEntity 

    

  /concepts/{id}:
    put: 
      tags:
        - Concept
      summary: Update an existing Concept
      operationId: updateConcept
      parameters: 
        - $ref: components/parameters/parameters.yml#/concept_id
      requestBody:
        description: Concept to update to the system
        content:
          application/json:
            schema:
              $ref: components/schemas/payloads/payload.yml#/ConceptPayload
      responses:
        '201':
          $ref: components/responses/responses.yml#/UpdatedConcept    
        '404':           
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 
        '422':
          $ref: components/responses/responses.yml#/UnprocessableEntity           

    delete:
      tags:
        - Concept
      summary: Delete an existing Concept
      operationId: deleteConcept
      parameters:
        - $ref: components/parameters/parameters.yml#/concept_id
      responses:
        '200':
          $ref: components/responses/responses.yml#/DeleteConcept      
        '404':          
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 

  /students/import:
    post:
      tags:
        - Student
      summary: Import students from xlsx file      
      operationId: importStudents 
      requestBody:
        description: Import students 
        content:
          multipart/form-data: 
            schema:
              $ref: components/schemas/payloads/payload.yml#/StudentImportPayload
      responses:
        '201':
          $ref: components/responses/responses.yml#/ImportStudents         
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 
        '422':
          $ref: components/responses/responses.yml#/UnprocessableEntityImport 

# Aplicar la API key globalmente a todas las operaciones 
security:
  - Authorization: []
            

components:
  # SECURITY
  # Contiene todos los tipos de seguridad para el uso del servicio  
  securitySchemes:
    # AUTHORIZATION:
    # Permite el uso del servicio mediante el registro de una api key enviado en el header
    # con el nombre Authorization, por ejemplo: Authorization EJm9IExSA9rv3N9uCVfIhNRdNOMUSe8w
    # estas cadenas serán colocadas en el archivo de configuración del servicio y restringido mediante un middleware
    Authorization:
      type: apiKey
      name: Authorization
      in: header 