openapi: '3.0.2'
info:
  title: System of Economy
  description: This service allows for control of the system's Economy
  version: "1.0"
  contact:
    name: Juan Alexis Luque Ayala
    email: juan.luque.ayala@gmail.com
servers:
  - url:  https://link.herokuapp.com/

tags:
  - name: PaymentConcept
    description: Everything about PaymentConcept

        
paths:
  #Modulo de PaymentConcepts
  /paymentConcepts:
    get:
      tags:
        - PaymentConcept    
      summary: Find all paymentConcepts
      operationId: listPaymentConcepts
      responses:            
        '200':
          $ref: components/responses/responses.yml#/ShowPaymentConcepts         
        '404':          
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 
          
          
    post:
      tags:
        - PaymentConcept    
      summary: Add a new paymentConcept to the system
      operationId: addPaymentConcept
      requestBody:
        description: PaymentConcept to add to the system
        content:
          application/json:
            schema:
              $ref: components/schemas/payloads/payload.yml#/PaymentConceptPayload
      responses:      
        '201':
          $ref: components/responses/responses.yml#/CreatedPaymentConcept         
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 
        '422':
          $ref: components/responses/responses.yml#/UnprocessableEntity 

    

  /paymentConcepts/{id}:
    put: 
      tags:
        - PaymentConcept
      summary: Update an existing paymentConcept
      operationId: updatePaymentConcept
      parameters: 
        - $ref: components/parameters/parameters.yml#/payment_concept_id
      requestBody:
        description: PaymentConcept to update to the system
        content:
          application/json:
            schema:
              $ref: components/schemas/payloads/payload.yml#/PaymentConceptPayload
      responses:
        '201':
          $ref: components/responses/responses.yml#/UpdatedPaymentConcept    
        '404':           
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 
        '422':
          $ref: components/responses/responses.yml#/UnprocessableEntity           

    delete:
      tags:
        - PaymentConcept
      summary: Delete an existing paymentConcept
      operationId: deletePaymentConcept
      parameters:
        - $ref: components/parameters/parameters.yml#/payment_concept_id
      responses:
        '200':
          $ref: components/responses/responses.yml#/DeletePaymentConcept      
        '404':          
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 
          
# Aplicar la API key globalmente a todas las operaciones 
security:
  - Authorization: []
            

components:
  # SECURITY
  # Contiene todos los tipos de seguridad para el uso del servicio  
  securitySchemes:
    # AUTHORIZATION:
    # Permite el uso del servicio mediante el registro de una api key enviado en el header
    # con el nombre Authorization, por ejemplo: Authorization EJm9IExSA9rv3N9uCVfIhNRdNOMUSe8w
    # estas cadenas serán colocadas en el archivo de configuración del servicio y restringido mediante un middleware
    Authorization:
      type: apiKey
      name: Authorization
      in: header 