
  # PARAMETERS
  #Contiene todos los parámetros que serán utilizados en una petición http ya sea que sea enviado
  #por el header, path, query o cache  
  # parameters:
    concept_id:
      name: id
      in: path
      required: true
      description: Concept id
      schema:
        type: integer 


   
    